# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75e7c19fc05f1cb7f99467bada0ea369d2a6a47471d214caa75885d689e37364bfca8e918d9318ddf83fbb60540e1b0540fe16622f2e89f75158368825144677

test:
  secret_key_base: 339562f93a9fd617689a0db06abd43f195130502f06a71b344acfeffbfadc7b687fcb5ec0ef4fd4755b2a9ef3f386c6436c83342a39d3a775f5fceddf395118f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
